### PR TITLE
233 implement new marker designs

### LINKED ISSUE #233: Implement New marker Designs
## Description
New marker dialogues have been designed here: https://xd.adobe.com/view/648e9731-3e23-49ca-af36-392065803fd1-31dd/screen/40651043-5839-4db2-8c5e-4fdbb019eaa3

https://xd.adobe.com/view/2f2fa6bb-d491-4de0-8784-383c23442dff-7a7c/grid/

Plus new layer and map saving dialogues here: https://xd.adobe.com/view/690fc910-3dad-4c7d-920f-621848a14038-3c5c/screen/75e0ba56-d099-43a4-b733-6b4f88887654

## Acceptance Criteria
- New designs implemented for dialogue boxes
- Unit tests where possible
- Dialogues are functional for lines, markers, polys
- No change to info box currently
- Editing works as now. No markdown rendering included yet. No WYSIWYG for input.
- All buttons - close, edit, linked maps, add to map - are functional as per now.

### PR DESCRIPTION
**Pull request by ms0ur1s**
#### What? Why?

Closes #233 

#### Implementation of new marker designs.
- Updates to the CSS and mark-up
- componentisation of DrawingPopup
- A little re-factoring and at least one bug fix

#### What should we test?
- Test the functionality of the new dialogue boxes across multiple devices. 
- Look out for any newly introduced bugs

For my own peace of mind I'll also be testing this once on staging.

### CODE REVIEW

**Comment by King-Mob** [comment]
@ms0ur1s is this meant to be in review? i can see i've been requested but it's in the in progress column

**Comment by ms0ur1s** [comment]
@King-Mob , thanks for the nudge man. Yes, this should have been in the review column.

**Review by King-Mob — APPROVED** [review]

**Comment by King-Mob** [comment]
@lin-d-hop there hasn't been a new PR attached to the issue since it went back to in progress. So, this PR is on staging but I don't think the content of the PR resolves the last comment on issue #233

**Comment by King-Mob** [comment]
@ms0ur1s @lin-d-hop should this be in review or QA or ready to go? currently in review but I'm not sure what I'm supposed to be reviewing

**Pull request merged**
