### PR TITLE
Save data group marker to map

### LINKED ISSUE #89: Add polys and markers to own map
## Description

Within markers and selectable polys (ie in commercial land reg data) we want a simple UI that enables the user to move this data to their own map.

This was discussed in a call on 01/08. Notes [here](https://docs.google.com/document/d/1V-0HH-JJAU6-RKqxDbvjTwrLnlSjHCzM0mhyVhnQvxs/edit).

## Acceptance Criteria
- A design both for polys (in land reg data) and for markers (eg in RGS data)
- Users should be able to add data to maps that have been shared with them and maps that they have saved already, as well as a new map
- If the user has than one map saved or shared with them they should be able to select which map this data should be saved to
- If the user currently is not on a saved map then they should have a helpful experience to select or save a map
- If the user has no maps saved or shared with them they should have a helpful experience to save a new map

### PR DESCRIPTION
**Pull request by King-Mob**
#### What? Why?

Closes #89

So people can add data group markers to their own maps.

#### What should we test?

Turn on a data group
click on a marker
click save icon in bottom right of pop-up
select map to save to
press save

map should have the marker in

#### Deployment notes

Make sure the item types table exists on the database before deploying

### CODE REVIEW

**Comment by lin-d-hop** [comment]
I can see the merge was to 'master' and not 'development' branch.

**Comment by lin-d-hop** [comment]
Unfortunately this doesn't seem to work:

1. When I click on selecting a map I seem to be taken straight to that map. C entered somewhere miles away from where I was
2. The marker is not added to that map.

Back to InDev

https://user-images.githubusercontent.com/8669848/198996969-5d9af666-0b5f-4430-9a0d-cf585c9c7d9e.mp4

**Comment by King-Mob** [comment]
@lin-d-hop try using a freshly created map

I can replicate what you're seeing only with an old saved map. I don't have a date boundary on it, but hopefully this can be solved with a migration because that's the only difference that I've found

**Comment by lin-d-hop** [comment]
Steps to reproduce:
1) Added line from Friends group to saved map
2) Opened saved map
3) Deleted the line from saved map
4) Turned the data layer back on
5) The line was removed from the data layer
Expected: The duplicated line was removed from the saved map but the line in the data layer should remain

Back to In Dev

**Comment by lin-d-hop** [comment]
Strange behaviour on renaming an element in a saved map:

Step to reproduce:
1) Add a poly to a saved map
2) Open the saved map
3) Rename the poly in the saved map
4) Create a new map
5) Turn on the data layer
6) The renamed poly has disappeared from the data layer

**Pull request merged**
