### PR TITLE
LX-247 Fix lingering polygons and featureId exception

### LINKED ISSUE #247: featureId error when editing a polygon
I’ve encountered this error locally and on staging. It is not present on live. My first thought was that I’d introduced it while working on my current issue, #230, but found it intermittently appearing on staging. Still attempting to map out the steps to recreate. When thrown this error prevents the selected polygon from being edited.

The account I used for the tests below is virgin, has never been used locally and is only being used on staging via incognito.

**Testing process**
1.	Created Map 1, added a polygon an edited directly after creation, no errors encountered. 
2.	Closed incognito (by accident without logging out), logged back in, selected this Map 1, received the featureId error - preventing the polygon from being edited.
3.	Created a second polygon on Map 1. 
4.	Managed to edit again immediately, no errors.
5.	Logged out and in again, and managed to edit the second polygon, no problem.
6.	I added a second polygon on test map, residual polygons from the previous map remained, but gone after I switched maps.*
7.	Edited this polygon, no problems.
8.	Switched from Map 2 to Map 1 attempted to edit the first polygon and received error. Same result with both polygons.
9.	Managed to switch back to the Map 2 and edit the polygon, error free.
10.	Again same result for both polygons on Map 1 after switching - featureId error.
11.	Again, polygon on Map 2 was editable after switching between maps.
12.	Created second polygon on Map 2.
13.	Immediately edited polygon
14.	After creating second polygon on Map 2 and switching between maps, and switching to Map 1, any attempt to edit a polygon on Map 1 still throws and error,
15.	Polygon 2 on Map 2 still editable.
16.	Created a third map, although both polygons from Map 2 are visible.  Neither is selectable.  
17.	Polygon created on Map 3 and immediately edited.
18.	After switching to Map 2 its polygons are still editable
19.	However the polygon from Map 3 is now also visible, and when I click on the map deselecting all polygons, then click edit in the left hand tray, all the polygons are given a blue outline, and I can edit the polygon from Map 3. 
20.	The native polygon on Map 3 three now errors when I attempt to edit it.
21.	Switching back to Map 2, Map3’s polygon has disappeared.
22.	Yet, Map 2's polygons still appear on Map 3.

**featureId errors**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTR0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7b50afc4757e9415ef2da459e9a6f8b04c421d3b/featureId_error_210823.jpg)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkl0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--12f64b9be762389b5264de33f014e6e071380330/featureId_error_210823_2.jpg)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdll0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--20997d64dc26cb9ecedd11e849004595fd35dece/featureId_error_210823_2.jpg)

**Polygon from third map visible on Map 2**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjh0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dc2a5d2e8421c95c3ccb6357bbde919a2b2dae50/Residual_polygons_on_second_from_new_3rd%20-%202nd_time_no_edit_possible.jpg)

**Polygon from third map made selectable on Map 2**

map 3 polygon selectable on map 2

**Polygon from third map being edited on Map 2**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ011IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--677d507acb51f45bd7c42b272c8734ae1551837a/Residual_polygons_editable_2nd_map.jpg)

### PR DESCRIPTION
**Pull request by rogup**
#### What? Why?

Closes #247

We are not redrawing the polygons properly when switching maps or opening new maps.
This is causing old polygons to linger but not be selectable/editable.
And it means that polygons in the new map throw an error when trying to edit them, since their feature IDs are not registered with mapbox.

I was able to reproduce this on both development and production by following these steps:
1. Draw a polygon
2. Open a map containing a different polygon
3. The first polygon lingers but is not selectable. The other polygon throws an error if you select it then click 'Edit'. (see logs in production since it throws an exception gracefully)

I'm pretty sure this is from all the refactoring work a few months ago (replacing component props with Redux and functionalising the Mapbox component), maybe mine oops. It's pretty serious, it seems basically most polygon functionality is broken...

To fix, I have ensured that we redraw polygons when the current map ID changes. And to cover the case when an unsaved map is replaced with a new map (so map ID remains null), I have introduced a temporary 'unsavedMapUuid' to distinguish between unsaved maps and also trigger a redraw. It feels a bit clanky to have such a variable in the redux store for just this purpose, but I couldn't think of a cleaner way to achieve this without adding a complicated sequence of Redux state changes.

#### What should we test?

- Follow the repro steps above

#### Release notes

I think this should go into the next release so that polygon functionality in prod is fixed ASAP

### CODE REVIEW

**Comment by rogup** [comment]
Hey @ms0ur1s good spot for this bug - please could you give my fix a review?

Also, maybe once it's merged, it would be worth you trying to repro the original scenario that found the bug on staging? I'm pretty sure I didn't follow all the steps completely accurately but ended up hitting the featureId exception by just playing around with some of my own maps.

**Review by ms0ur1s — APPROVED** [review]

**Comment by rogup** [comment]
Thanks for reviewing @ms0ur1s ! I've just merged so it will be ready to test on staging in a few mins.
Also, just to let you know, feel free to merge and move to QA any PRs that I send to you for review, once they're approved

**Comment by ms0ur1s** [comment]
NIce one @rogup , I'll give it a test. 

Cool, I'll follow that procedure from now on.

**Comment by ms0ur1s** [comment]
@rogup, tested on development branch using three different accounts (two existing and one new), each with multiple saved maps with custom polygons.

* Switched between each map to check for bleed through of polygons from other maps
* Edited polygons on each map, checking whether editing was possible and for the appearance of the featureId error noted in #247.
* Successfully created new polygons on existing maps, without errors or bleed through
* Created a new map, added polygons, changed map, returned to the new map and edited polygons
* Deleted polygons from existing maps
* Created new account and re-tested the above

Works perfectly, all tests passed on dev, ready for staging.

**Comment by lin-d-hop** [comment]
Great work team, spotting and fixing this!
LGTM :)

**Pull request merged**
